import 'saved_exercise.dart';

/// Default exercise library - 10 most popular exercises per muscle group.
/// These are seeded on first launch and skip any exercises whose name
/// already exists in the user's library.
class DefaultExercises {
  static List<SavedExercise> get all => [
    // ============ CHEST (10) ============
    SavedExercise(
      id: 'default_ex_chest_1',
      name: 'Barbell Bench Press',
      muscleGroup: 'Chest',
      defaultSets: 4,
      defaultMinReps: 6,
      defaultMaxReps: 10,
      notes: 'Keep feet flat, arch back slightly, retract shoulder blades. Control the descent.',
    ),
    SavedExercise(
      id: 'default_ex_chest_2',
      name: 'Incline Dumbbell Press',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Set bench to 30-45 degrees. Focus on upper chest activation.',
    ),
    SavedExercise(
      id: 'default_ex_chest_3',
      name: 'Dumbbell Flat Bench Press',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Greater range of motion than barbell. Keep dumbbells in line with mid-chest.',
    ),
    SavedExercise(
      id: 'default_ex_chest_4',
      name: 'Cable Chest Fly',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Set cables at shoulder height. Slight bend in elbows, squeeze at the center.',
    ),
    SavedExercise(
      id: 'default_ex_chest_5',
      name: 'Chest Press Machine',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Great bench press alternative when benches are taken. Adjust seat so handles are at mid-chest.',
    ),
    SavedExercise(
      id: 'default_ex_chest_6',
      name: 'Push-Ups',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 20,
      notes: 'Body straight from head to heels. Full range of motion.',
    ),
    SavedExercise(
      id: 'default_ex_chest_7',
      name: 'Decline Bench Press',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Targets lower chest. Use a spotter or smith machine for safety.',
    ),
    SavedExercise(
      id: 'default_ex_chest_8',
      name: 'Dumbbell Chest Fly',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Slight bend in elbows throughout. Lower until stretch is felt, squeeze at top.',
    ),
    SavedExercise(
      id: 'default_ex_chest_9',
      name: 'Dips (Chest)',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Lean forward to target chest. Go to 90 degrees elbow bend.',
    ),
    SavedExercise(
      id: 'default_ex_chest_10',
      name: 'Pec Deck Machine',
      muscleGroup: 'Chest',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Keep elbows at 90 degrees. Squeeze pecs at the center.',
    ),

    // ============ BACK (10) ============
    SavedExercise(
      id: 'default_ex_back_1',
      name: 'Barbell Deadlift',
      muscleGroup: 'Back',
      defaultSets: 4,
      defaultMinReps: 5,
      defaultMaxReps: 8,
      notes: 'Hinge at hips, keep back flat, drive through heels. Bar stays close to body.',
    ),
    SavedExercise(
      id: 'default_ex_back_2',
      name: 'Pull-Ups',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 5,
      defaultMaxReps: 12,
      notes: 'Overhand grip, pull chest to bar. Use assisted machine if needed.',
    ),
    SavedExercise(
      id: 'default_ex_back_3',
      name: 'Barbell Bent Over Row',
      muscleGroup: 'Back',
      defaultSets: 4,
      defaultMinReps: 6,
      defaultMaxReps: 10,
      notes: 'Hinge at 45 degrees, pull bar to lower chest. Squeeze shoulder blades.',
    ),
    SavedExercise(
      id: 'default_ex_back_4',
      name: 'Lat Pulldown',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Wide grip, pull to upper chest. Lean back slightly.',
    ),
    SavedExercise(
      id: 'default_ex_back_5',
      name: 'Seated Cable Row',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Sit upright, pull handle to lower chest. Squeeze shoulder blades together.',
    ),
    SavedExercise(
      id: 'default_ex_back_6',
      name: 'Dumbbell Single Arm Row',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'One knee and hand on bench. Pull dumbbell to hip, squeeze lat at top.',
    ),
    SavedExercise(
      id: 'default_ex_back_7',
      name: 'T-Bar Row',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Straddle the bar, close grip. Pull to chest, squeeze back.',
    ),
    SavedExercise(
      id: 'default_ex_back_8',
      name: 'Face Pulls',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 20,
      notes: 'Cable at face height, rope attachment. Pull to face, externally rotate at end.',
    ),
    SavedExercise(
      id: 'default_ex_back_9',
      name: 'Chin-Ups',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 5,
      defaultMaxReps: 12,
      notes: 'Underhand grip, slightly narrower than shoulders. Also hits biceps.',
    ),
    SavedExercise(
      id: 'default_ex_back_10',
      name: 'Hyperextensions',
      muscleGroup: 'Back',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Targets lower back. Cross arms over chest or hold plate. Controlled movement.',
    ),

    // ============ SHOULDERS (10) ============
    SavedExercise(
      id: 'default_ex_shoulders_1',
      name: 'Overhead Press',
      muscleGroup: 'Shoulders',
      defaultSets: 4,
      defaultMinReps: 6,
      defaultMaxReps: 10,
      notes: 'Standing or seated. Press bar from shoulders to overhead. Brace core.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_2',
      name: 'Dumbbell Shoulder Press',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Seated on incline bench at 90 degrees. Press dumbbells overhead.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_3',
      name: 'Lateral Raises',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Slight bend in elbows. Raise to shoulder height, control the descent.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_4',
      name: 'Front Raises',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Dumbbells or plate. Raise to shoulder height, alternate or both arms.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_5',
      name: 'Reverse Pec Deck (Rear Delts)',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 15,
      notes: 'Face the machine. Squeeze rear delts to pull handles back.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_6',
      name: 'Arnold Press',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Start palms facing you, rotate as you press up. Hits all three delt heads.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_7',
      name: 'Cable Lateral Raises',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Constant tension throughout. Cross-body with low cable.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_8',
      name: 'Upright Row',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Barbell or dumbbells. Pull to chin level, elbows high. Avoid if shoulder issues.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_9',
      name: 'Shoulder Press Machine',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Good alternative when free weights are taken. Adjust seat height.',
    ),
    SavedExercise(
      id: 'default_ex_shoulders_10',
      name: 'Bent Over Reverse Fly',
      muscleGroup: 'Shoulders',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 15,
      notes: 'Hinge forward, slight bend in elbows. Targets rear delts.',
    ),

    // ============ BICEPS (10) ============
    SavedExercise(
      id: 'default_ex_biceps_1',
      name: 'Barbell Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Keep elbows pinned to sides. Full extension at bottom, squeeze at top.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_2',
      name: 'Dumbbell Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Alternate or both arms. Supinate (twist) at the top for peak contraction.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_3',
      name: 'Hammer Curls',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Neutral grip (palms facing each other). Targets brachialis and forearms.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_4',
      name: 'Incline Dumbbell Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Bench at 45 degrees. Greater stretch on bicep long head.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_5',
      name: 'Preacher Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'EZ bar or dumbbells. Pad prevents cheating. Full range of motion.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_6',
      name: 'Cable Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Constant tension throughout the movement. Straight bar or rope.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_7',
      name: 'Concentration Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Seated, elbow braced against inner thigh. Isolates the bicep.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_8',
      name: 'EZ Bar Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Angled grip is easier on wrists than straight bar.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_9',
      name: 'Spider Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Chest against incline bench, arms hanging straight down. No momentum.',
    ),
    SavedExercise(
      id: 'default_ex_biceps_10',
      name: 'Machine Bicep Curl',
      muscleGroup: 'Biceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Good for isolating biceps with consistent resistance.',
    ),

    // ============ TRICEPS (10) ============
    SavedExercise(
      id: 'default_ex_triceps_1',
      name: 'Tricep Pushdown',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Cable with straight bar or V-bar. Keep elbows locked at sides.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_2',
      name: 'Skull Crushers',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'EZ bar or dumbbells. Lower to forehead, extend to lockout. Keep elbows in.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_3',
      name: 'Close Grip Bench Press',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Hands shoulder-width or narrower. Targets triceps more than chest.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_4',
      name: 'Overhead Tricep Extension',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Dumbbell or cable. Arms overhead, lower behind head, extend up.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_5',
      name: 'Rope Pushdown',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Spread the rope at the bottom for extra contraction.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_6',
      name: 'Dips (Tricep)',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Stay upright (don\'t lean forward). Elbows close to body.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_7',
      name: 'Tricep Kickback',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Bend forward, extend dumbbell back until arm is straight. Squeeze at top.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_8',
      name: 'Diamond Push-Ups',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 15,
      notes: 'Hands together forming a diamond. Bodyweight tricep exercise.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_9',
      name: 'Bench Dips',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Hands on bench behind you. Lower body down, press back up.',
    ),
    SavedExercise(
      id: 'default_ex_triceps_10',
      name: 'Tricep Press Machine',
      muscleGroup: 'Triceps',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Consistent resistance. Good for burnout sets.',
    ),

    // ============ LEGS (10) ============
    SavedExercise(
      id: 'default_ex_legs_1',
      name: 'Barbell Back Squat',
      muscleGroup: 'Legs',
      defaultSets: 4,
      defaultMinReps: 6,
      defaultMaxReps: 10,
      notes: 'Bar on upper traps. Break at hips and knees together. Depth to parallel or below.',
    ),
    SavedExercise(
      id: 'default_ex_legs_2',
      name: 'Leg Press',
      muscleGroup: 'Legs',
      defaultSets: 4,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Feet shoulder-width, mid-platform. Don\'t lock knees at top.',
    ),
    SavedExercise(
      id: 'default_ex_legs_3',
      name: 'Romanian Deadlift',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Hinge at hips, slight knee bend. Feel stretch in hamstrings. Bar close to legs.',
    ),
    SavedExercise(
      id: 'default_ex_legs_4',
      name: 'Leg Curl Machine',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Lying or seated. Control the movement, squeeze hamstrings at top.',
    ),
    SavedExercise(
      id: 'default_ex_legs_5',
      name: 'Leg Extension Machine',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Isolates quadriceps. Squeeze at the top, slow descent.',
    ),
    SavedExercise(
      id: 'default_ex_legs_6',
      name: 'Walking Lunges',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 14,
      notes: 'Reps per leg. Long stride, back knee near floor. Dumbbells or bodyweight.',
    ),
    SavedExercise(
      id: 'default_ex_legs_7',
      name: 'Front Squat',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 6,
      defaultMaxReps: 10,
      notes: 'Bar on front delts, elbows high. More quad-dominant than back squat.',
    ),
    SavedExercise(
      id: 'default_ex_legs_8',
      name: 'Bulgarian Split Squat',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Rear foot elevated on bench. Dumbbells at sides. Per leg.',
    ),
    SavedExercise(
      id: 'default_ex_legs_9',
      name: 'Hack Squat Machine',
      muscleGroup: 'Legs',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Back against pad, feet shoulder-width. Good squat alternative.',
    ),
    SavedExercise(
      id: 'default_ex_legs_10',
      name: 'Calf Raises',
      muscleGroup: 'Legs',
      defaultSets: 4,
      defaultMinReps: 12,
      defaultMaxReps: 20,
      notes: 'Standing or seated. Full stretch at bottom, squeeze at top. Slow reps.',
    ),

    // ============ GLUTES (10) ============
    SavedExercise(
      id: 'default_ex_glutes_1',
      name: 'Hip Thrust',
      muscleGroup: 'Glutes',
      defaultSets: 4,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Upper back on bench, barbell on hips. Drive hips up, squeeze glutes at top.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_2',
      name: 'Glute Bridge',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 15,
      notes: 'Lying on floor, feet flat. Drive hips up. Add weight on hips for resistance.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_3',
      name: 'Cable Kickback',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Ankle strap on low cable. Kick back and squeeze glute. Per leg.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_4',
      name: 'Sumo Deadlift',
      muscleGroup: 'Glutes',
      defaultSets: 4,
      defaultMinReps: 6,
      defaultMaxReps: 10,
      notes: 'Wide stance, toes pointed out. Grip between legs. Hits glutes and inner thighs.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_5',
      name: 'Step-Ups',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 12,
      notes: 'Bench or box height. Drive through heel. Dumbbells or bodyweight. Per leg.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_6',
      name: 'Glute Ham Raise',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'GHD machine. Lower body forward, pull back with hamstrings and glutes.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_7',
      name: 'Single Leg Deadlift',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Dumbbell in opposite hand. Hinge forward on one leg. Great for balance.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_8',
      name: 'Abduction Machine',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 20,
      notes: 'Push knees apart against pads. Targets glute medius.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_9',
      name: 'Banded Clamshells',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 15,
      defaultMaxReps: 20,
      notes: 'Side lying, resistance band above knees. Open knees like a clamshell.',
    ),
    SavedExercise(
      id: 'default_ex_glutes_10',
      name: 'Donkey Kicks',
      muscleGroup: 'Glutes',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 15,
      notes: 'On all fours. Drive heel toward ceiling. Band or cable for added resistance.',
    ),

    // ============ CORE (10) ============
    SavedExercise(
      id: 'default_ex_core_1',
      name: 'Plank',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 30,
      defaultMaxReps: 60,
      notes: 'Reps = seconds. Forearms on ground, body straight. Brace abs.',
    ),
    SavedExercise(
      id: 'default_ex_core_2',
      name: 'Hanging Leg Raise',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 15,
      notes: 'Hang from bar, raise legs to 90 degrees. Avoid swinging.',
    ),
    SavedExercise(
      id: 'default_ex_core_3',
      name: 'Cable Woodchop',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'High to low or low to high. Rotate through core, not arms. Per side.',
    ),
    SavedExercise(
      id: 'default_ex_core_4',
      name: 'Ab Wheel Rollout',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'From knees, roll out as far as possible, pull back. Keep core tight.',
    ),
    SavedExercise(
      id: 'default_ex_core_5',
      name: 'Russian Twist',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 15,
      defaultMaxReps: 20,
      notes: 'Seated, feet off ground. Rotate side to side with weight. Per side.',
    ),
    SavedExercise(
      id: 'default_ex_core_6',
      name: 'Bicycle Crunches',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 15,
      defaultMaxReps: 20,
      notes: 'Opposite elbow to knee. Controlled movement, don\'t pull on neck.',
    ),
    SavedExercise(
      id: 'default_ex_core_7',
      name: 'Dead Bug',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'On back, extend opposite arm and leg. Keep lower back pressed to floor. Per side.',
    ),
    SavedExercise(
      id: 'default_ex_core_8',
      name: 'Pallof Press',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 10,
      defaultMaxReps: 15,
      notes: 'Cable at chest height. Press out and resist rotation. Anti-rotation exercise.',
    ),
    SavedExercise(
      id: 'default_ex_core_9',
      name: 'Decline Sit-Ups',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 20,
      notes: 'Decline bench, feet hooked. Cross arms over chest or hold plate.',
    ),
    SavedExercise(
      id: 'default_ex_core_10',
      name: 'Mountain Climbers',
      muscleGroup: 'Core',
      defaultSets: 3,
      defaultMinReps: 20,
      defaultMaxReps: 30,
      notes: 'Push-up position, drive knees to chest alternating. Reps per side.',
    ),

    // ============ FULL BODY (10) ============
    SavedExercise(
      id: 'default_ex_fullbody_1',
      name: 'Barbell Clean and Press',
      muscleGroup: 'Full Body',
      defaultSets: 4,
      defaultMinReps: 5,
      defaultMaxReps: 8,
      notes: 'Clean from floor to shoulders, then press overhead. Full body compound.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_2',
      name: 'Thrusters',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Front squat into overhead press in one movement. Barbell or dumbbells.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_3',
      name: 'Burpees',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 15,
      notes: 'Squat down, kick back to plank, push-up, jump up. Full body conditioning.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_4',
      name: 'Kettlebell Swing',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 12,
      defaultMaxReps: 20,
      notes: 'Hip hinge movement. Drive hips forward to swing kettlebell to shoulder height.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_5',
      name: 'Turkish Get-Up',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 3,
      defaultMaxReps: 5,
      notes: 'Kettlebell or dumbbell. Complex movement from lying to standing. Per side.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_6',
      name: 'Farmer\'s Walk',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 30,
      defaultMaxReps: 60,
      notes: 'Reps = seconds (or steps). Heavy dumbbells at sides, walk with good posture.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_7',
      name: 'Battle Ropes',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 20,
      defaultMaxReps: 30,
      notes: 'Reps = seconds. Alternating waves, slams, or circles. Full body conditioning.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_8',
      name: 'Man Makers',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 5,
      defaultMaxReps: 8,
      notes: 'Push-up, row each arm, clean to standing, press overhead. Intense compound.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_9',
      name: 'Sled Push',
      muscleGroup: 'Full Body',
      defaultSets: 4,
      defaultMinReps: 1,
      defaultMaxReps: 1,
      notes: 'Load sled, push for distance (20-40 yards). Reps = trips. Full body power.',
    ),
    SavedExercise(
      id: 'default_ex_fullbody_10',
      name: 'Box Jumps',
      muscleGroup: 'Full Body',
      defaultSets: 3,
      defaultMinReps: 8,
      defaultMaxReps: 12,
      notes: 'Jump onto box, step down. Focus on explosive hip extension. Start low.',
    ),
  ];
}
